### ISSUE TITLE
Can't reset or set value

### ISSUE THREAD

**Issue by 404nfii** [VirtusX/fstdropdown#4]
I'm using code 
$("#form")[0].reset();
to reset form, but fst option not effect, as well as use .value=""; to set value

**Comment by VirtusX** [comment]
Unfortunatelly, there is no way to detect reset or modifying value by javascript.
I added function document.getElementById("your select").fstdropdown.setValue() to set value, you can see examples [here](https://htmlpreview.github.io/?https://github.com/VirtusX/fstdropdown/blob/master/index.html)
Or you can refresh select after changing value by document.getElementById("your select").fstdropdown.rebind()

**Comment by 404nfii** [comment]
ok, it's works.
thans
